### ISSUE TITLE
iSpeech ASR return status = -1 always

### ISSUE THREAD

**Issue by andreabianco** [zaf/asterisk-ispeech#2]
Hi!

I'm using your script in order to use iSpeech ASR with Asterisk, but it doesn't work.
It return status=-1 always and the error is "result=error&code=995&message=No+data+in+post+payload".

I read the iSpeech ASR documentation and I think the error is related to the type of HTTP request because if I change to GET it works.

**Comment by zaf** [comment]
Thank you for the report, fix apiled to ASR script
